NAME		=	PhoneBook

CC			=	g++ -std=c++98

CXXFLAGS	=	-Wall -Wextra -Werror -g #-fsanitize=address -fsanitize=undefined

SRCS		=	main.cpp \
				Contact.cpp \
				PhoneBook.cpp

OBJS		=	${SRCS:.cpp=.o}

all: ${NAME}

${NAME}: ${OBJS}
	@echo "Compiling..."
	@${CC} ${CXXFLAGS} -o $@ $^ 
	@echo "PhoneBook compiled"

%.o: %.cpp
	@$(CC) $(CXXFLAGS) -c -o $@ $<

clean:
	@rm -rf ${OBJS}
	@echo "Objects removed"

fclean: clean
	@rm -rf ${NAME}
	@echo "PhoneBook removed"

re: fclean all

.PHONY: all clean fclean re